#Сухожилия плоти
- type: entity
  id: FleshWeb
  name: сухожилия плоти
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
    - type: DamageContacts
      damage:
        groups:
          Brute: -0.5
          Burn: -0.5
          Airloss: -0.5
          Toxin: -0.5
          Genetic: -0.5
      ignoreWhitelist:
        tags:
        - AnomalyHost
        - CannotSuicide
        - VimPilot
    - type: MeleeSound
      soundGroups:
        Brute:
          path:
            "/Audio/Weapons/slash.ogg"
    - type: Sprite
      sprite: Adventure/Roles/flesh.rsi
      layers:
        - state: meat
          map: ["spiderWebLayer"]
      drawdepth: FloorTiles
    - type: Appearance
    - type: Clickable
    - type: Transform
      anchored: true
    - type: Physics
    - type: Fixtures
      fixtures:
        fix1:
          hard: false
          density: 7
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5,-0.5,0.5,0.5"
          layer:
          - MidImpassable
    - type: Damageable
      damageModifierSet: Devourer
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 30
        behaviors:
        - !type:DoActsBehavior
          acts: [ "Destruction" ]
        - !type:SpawnEntitiesBehavior
          spawn:
            FoodMeat:
              min: 1
              max: 2
    - type: Temperature
      heatDamage:
        types:
          Heat: 5
      coldDamage:
        types:
          Cold: 5
    - type: Barotrauma
      damage:
        types:
          Blunt: 0.10
    - type: AtmosExposed
    - type: Flammable
      fireSpread: true
      damage:
       types:
         Heat: 3
    - type: Respirator
      damage:
        types:
          Asphyxiation: 0.25
      damageRecovery:
        types:
          Asphyxiation: -0.25
    - type: SpeedModifierContacts
      walkSpeedModifier: 0.5
      sprintSpeedModifier: 0.5
      ignoreWhitelist:
        tags:
        - Flesh
    - type: EmitSoundOnSpawn
      sound:
        path: /Audio/Adventure/flesh/slime_Spawn.ogg

#Строительство сухожилий
- type: entity
  id: ActionFleshWeb
  name: Пустить сухожилия
  description: Распространяйте сухожилия, чтобы замедлить ваших врагов и восстановить здоровье.
  noSpawn: true
  components:
  - type: InstantAction
    icon:
      sprite: Adventure/Roles/flesh.rsi
      state: meat
    event: !type:SpiderWebActionEvent
    useDelay: 25