- type: entity
  id: FleshSpawnerOFF
  parent: BaseStructure
  name: матка плоти
  description: что же внутри?
  components:
  - type: PointLight
    radius: 2
    energy: 2
    color: "#73c536"
  - type: InteractionOutline
  - type: Sprite
    noRot: true
    sprite: Adventure/Roles/flesh.rsi
    layers:
    - state: Spawners_off
      map: [ "enum.DamageStateVisualLayers.Base" ]
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.3
        density: 190
        mask:
        - TableMask
        layer:
        - TableLayer
  - type: Damageable
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 30
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          FoodMeat:
            min: 1
            max: 1
  - type: Temperature
    heatDamage:
      types:
        Heat: 5
    coldDamage:
      types:
        Cold: 5
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.10
  - type: AtmosExposed
  - type: Flammable
    fireSpread: true
    damage:
      types:
        Heat: 3
  - type: Respirator
    damage:
      types:
        Asphyxiation: 0.25
    damageRecovery:
      types:
        Asphyxiation: -0.25

- type: entity
  id: FleshSpawnerSpawn
  parent: FleshSpawnerOFF
  components:
  - type: Sprite
    noRot: true
    sprite: Adventure/Roles/flesh.rsi
    layers:
    - state: Spawners
      map: [ "enum.DamageStateVisualLayers.Base" ]
  - type: SpawnOnDespawn
    prototype: FleshSpawnerOFF
  - type: Timer
  - type: TimedSpawner
    prototypes:
    - MobFleshJared
    - MobFleshClamp
    - MobFleshLover
    - MobFleshGolem
    intervalSeconds: 2
    minimumEntitiesSpawned: 1
    maximumEntitiesSpawned: 1
  - type: TimedDespawn
    lifetime: 2.5
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/flesh/slime_Spawn.ogg

- type: entity
  id: FleshSpawner
  parent: FleshSpawnerOFF
  components:
  - type: Sprite
    noRot: true
    sprite: Adventure/Roles/flesh.rsi
    layers:
    - state: Spawners
      map: [ "enum.DamageStateVisualLayers.Base" ]
  - type: Timer
  - type: TimedSpawner
    prototypes:
    - FleshSpawnerSpawn
    intervalSeconds: 120
    minimumEntitiesSpawned: 1
    maximumEntitiesSpawned: 1
  - type: TimedDespawn
    lifetime: 121
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/flesh/slime_Spawn.ogg

#Строительство матки
- type: entity
  id: ActionSpawnFleshSpawners
  name: Построить матку плоти
  description: Органические матки рождают существ плоти.
  noSpawn: true
  components:
  - type: WorldTargetAction
    useDelay: 60
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/flesh.rsi
      state: Spawners
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: FleshSpawner
        amount: 1