using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Utility;

namespace Content.Client._Adventure.DiscordMember;

[GenerateTypedNameReferences]
public sealed partial class DiscordMemberGui : Control
{
    [Dependency] private readonly DiscordAuthManager _discordAuth = default!;
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    public DiscordMemberGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += (_) =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        UrlEdit.TextRope = new Rope.Leaf(_discordAuth.DiscordUrl);
        if (_discordAuthManager.DiscordQrcode != null)
        {
            QrCode.Texture = _discordAuth.DiscordQrcode;
        }

        if (_discordAuth.DiscordUsername != string.Empty)
        {
            DiscordUsername.Text = _discordAuth.DiscordUsername;
        }

        OpenUrlButton.OnPressed += (_) =>
        {
            if (_discordAuth.DiscordUrl != string.Empty)
            {
                IoCManager.Resolve<IUriOpener>().OpenUri(_discordAuth.DiscordUrl);
            }
        };
    }
}
