using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Adventure.Administration.SponsorChange;

[GenerateTypedNameReferences]
public sealed partial class SponsorChangeWindow : FancyWindow
{
    public SponsorChangeWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
